title: Signal & Image Processing Lab
description: >-
  Repository for S&IP Lab codes
baseurl: "/Signal_ImageProcessing-Lab"
url: "https://ashrithsagar.github.io"
github_username:  AshrithSagar

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  experiments:
    output: true
    permalink: /:collection/:path/
